language: go
os:
    - linux
    #- osx
go:
    - "1.10"
    - tip
install:
    - go get github.com/goforgery/forgery2
    - go get github.com/tarm/serial
    - go get github.com/ricallinson/simplebdd
    - go get github.com/goforgery/mustache
    - go get github.com/goforgery/static
