language: go
go:
    - 1.3.3 # Pi version
    - 1.8 # Latest stable
    - tip
install:
    - go get github.com/goforgery/forgery2
    - go get github.com/tarm/serial
    - go get github.com/ricallinson/simplebdd
    - go get github.com/goforgery/mustache
    - go get github.com/goforgery/static
