language: go
go:
    - 1.5
    - 1.6
    - tip
install:
    - go get github.com/goforgery/forgery2
    - go get github.com/tarm/serial
    - go get github.com/ricallinson/simplebdd
    - go get github.com/goforgery/mustache
